server:
  port: 8087

spring:
  application:
    name: pushs
  kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: gr1
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: com.example.push_notification_service.util.CustomJsonDeserializer
        properties:
          spring.json.type.mapping: "News:com.example.push_notification_service.models.News"
          spring.json.trusted.packages: "*"
          #spring:
          #  json:
          #    trusted:
          #      packages : "*"

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8080/eureka