spring:
 cloud:
   gateway:
     routes:
       - id: Auth_service
         uri: lb://auths
         predicates:
           - Path=/auth/**
         filters:
           - RateLimitFilter


       - id: Auth_service
         uri: lb://auths
         predicates:
           - Path=/getAuth/**
         filters:
           - AuthenticationFilter

       - id: Group_service
         uri: lb://groups
         predicates:
           - Path=/group/**
         filters:
           - AuthenticationFilter

       - id: Messenger_service_chat
         uri: lb://messengers
         predicates:
           - Path=/chat/**
         filters:
           - AuthenticationFilter

       - id: Messenger_service_message
         uri: lb://messengers
         predicates:
           - Path=/message/**
         filters:
           - AuthenticationFilter

       - id: News_service
         uri: lb://newss
         predicates:
           - Path=/news/**
         filters:
           - AuthenticationFilter

       - id: Image_service
         uri: lb://images
         predicates:
           - Path=/image/**
         filters:
           - AuthenticationFilter

       - id: Administrative_service
         uri: lb://admins
         predicates:
           - Path=/admin/**
         filters:
           - AuthenticationFilter

       - id: Administrative_service
         uri: lb://admins
         predicates:
           - Path=/info/**
         filters:
           - AuthenticationFilter

       - id: Exam_service
         uri: lb://exams
         predicates:
           - Path=/event/**
         filters:
           - AuthenticationFilter

       - id: Teacher_service
         uri: lb://teachers
         predicates:
           - Path=/curriculum/**
         filters:
           - AuthenticationFilter

       - id: Teacher_service
         uri: lb://teachers
         predicates:
           - Path=/teacher/**
         filters:
           - AuthenticationFilter

       - id: Club_service
         uri: lb://clubs
         predicates:
           - Path=/club/**
         filters:
           - AuthenticationFilter

       - id: Statistics_service
         uri: lb://statistics
         predicates:
           - Path=/statistic/**
         filters:
           - AuthenticationFilter

       - id: Exam_Taller_Service
         uri: lb://examtaller
         predicates:
           - Path=/main/**
         filters:
           - AuthenticationFilter

       - id: Video_service
         uri: lb://videose
         predicates:
           - Path=/video/**
         filters:
           - AuthenticationFilter

       - id: Video_service
         uri: lb://videose
         predicates:
           - Path=/videos/**
         filters:
           - AuthenticationFilter
 application:
   name: Gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8080/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
