server:
  port: 8084

spring:
  application:
    name: messengers
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.messenger_service.util.CustomJsonSerializer

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8080/eureka